# This file generates legal notices as PDFs

from groq import Groq

from reportlab.lib.pagesizes import A4

from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle

from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer 

from reportlab.lib.units import inch
# 1 inch = 72 points in PDF measurements

from reportlab.lib import colors

import io
import os
from dotenv import load_dotenv
load_dotenv()

def generate_notice_text(situation:str)->str:
    client=Groq(api_key=os.getenv("GROQ_API_KEY"))
    prompt= f"""You are a legal notice drafting expert in India.
Draft a formal legal notice based on this situation:

{situation}

The notice must follow this exact format (do NOT include "LEGAL NOTICE" as a heading — it will be added separately):
1. Date (use today's date)
2. "To," followed by recipient details (extract from situation or use placeholder)
3. "From," followed by sender details (extract from situation or use placeholder)
4. "Subject:" line
5. Body with numbered paragraphs explaining:
   - The background/facts
   - The legal violation with specific IPC/relevant law sections
   - The demand/relief sought
   - Consequences if not complied with (legal action)
6. End with timeframe (usually 15 days to comply)
7. "Yours faithfully" and signature line

Make it formal, professional and legally sound.
Use actual Indian law sections where relevant.
Do NOT add any heading, title, or "LEGAL NOTICE" text at the top — start directly with the date.
"""
    response=client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role":"user","content":prompt}]
    )
    return response.choices[0].message.content

#It gives the text content of the first AI response generated by the model.

def create_notice_pdf(notice_text:str,filename:str="legal_notice.pdf")->bytes:
    buffer=io.BytesIO()
    doc=SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.2*inch,
        leftMargin=1.2*inch,
        topMargin=1*inch,
        bottomMargin=1*inch
    )
    styles=getSampleStyleSheet()
    # getSampleStyleSheet() gives us default styles
    # styles['Normal'] — regular paragraph text
    # styles['Heading1'] — large heading
    # styles['Heading2'] — medium heading

    title_style=ParagraphStyle(
        'TitleStyle',
        parent=styles['Normal'],
        fontSize=18,
        fontName='Helvetica-Bold',
        alignment=1,
        spaceAfter=6,
        textColor=colors.black,
        underlineProportion=0.05
    )

    # Subtitle style — smaller centered underlined

    subtitle_style=ParagraphStyle(
        'SubtitleStyle',
        parent=styles['Normal'],
        fontSize=12,
        fontName='Helvetica-Bold',
        alignment=1,
        spaceAfter=20,
        underline=True
    )
    # Date and address style

    address_style=ParagraphStyle(
        'AddressStyle',
        parent=styles['Normal'],
        fontSize=11,
        fontName='Helvetica',
        leading=18,
        spaceAfter=6
    )
    # Subject style — bold

    subject_style=ParagraphStyle(
        'SubjectStyle',
        parent=styles['Normal'],
        fontSize=11,
        fontName='Helvetica-Bold',
        leading=18,
        spaceAfter=16
    )
    #body style - normal lopla body text

    body_style=ParagraphStyle(
        'BodyStyle',
        parent=styles["Normal"],
        fontSize=11,
        fontName='Helvetica',
        leading=20,
        # leading is line height — space between lines
        # 20 points = comfortable reading space
        firstLineIndent=0
        
    )
    #closing style
    closing_style=ParagraphStyle(
        'ClosingStyle',
        parent=styles['Normal'],
        fontSize=11,
        fontName='Helvetica',
        leading=20,
        spaceBefore=20,
        spaceAfter=6
    )

    story=[]
    # story is the list of elements that go into the PDF
    # we add elements one by one
    # reportlab reads this list and builds the PDF

    from reportlab.platypus import HRFlowable
    story.append(HRFlowable(width="100%",thickness=2,color=colors.black))
    story.append(Spacer(1,0.15*inch))

    story.append(Paragraph("LEGAL NOTICE",title_style))
    story.append(Paragraph("(Without Prejudice)", subtitle_style))

    story.append(HRFlowable(width="100%", thickness=1, color=colors.black))

    story.append(Spacer(1,0.2*inch))
    # Spacer(width, height)
    # add some space after the title

    lines=notice_text.split('\n')

    for line in lines:
        stripped=line.strip()

        if not stripped:
            story.append(Spacer(1,0.08*inch))
            continue
        #special chars teesesthe better

        clean=stripped.replace('&','&amp;').replace('<','&lt;').replace('>','&gt;')

        if stripped.upper()=='LEGAL NOTICE':
            continue
        elif stripped.startswith('Subject:') or stripped.startswith('SUBJECT:'):        #subject bold cheyaniki
            story.append(Paragraph(f"<u><b>{clean}</b></u>",subject_style))
        elif stripped.startswith('To,') or stripped.startswith('From,'):
            story.append(Paragraph(f"<b>{clean}</b>",address_style))
        elif stripped.startswith('Yours') or stripped.startswith('yours'):   #closing line
            story.append(Paragraph(clean,closing_style))
        else:
            story.append(Paragraph(clean,address_style))        

    story.append(Spacer(1, 0.3*inch))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.black))        
    doc.build(story)
    # build() takes our story list and generates the actual PDF
    # writes it to our buffer          
    pdf_bytes=buffer.getvalue()
    buffer.close()
    return pdf_bytes

def generate_legal_notice(situation:str)->bytes:
    notice_text=generate_notice_text(situation)

    pdf_bytes=create_notice_pdf(notice_text)

    return pdf_bytes


